version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

executors:
  clj:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-17.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
  cljs:
    docker:
      - image: cimg/clojure:1.11.1-node
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
        
jobs:
  test-script-lib:
    executor: clj
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "lib/deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Dependencies
          command: clojure -X:test:junit:deps prep
          working_directory: lib
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "lib/deps.edn" }}
      - run:
          name: Unit tests
          command: clojure -X:test:junit
          working_directory: lib
      - store_test_results:
          path: lib/junit.xml

  deploy-script-lib:
    executor: clj
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "lib/deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Dependencies
          command: clojure -X:jar:deps prep
          working_directory: lib
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "lib/deps.edn" }}
      - run:
          name: Build Jar
          command: clojure -X:jar
          working_directory: lib
      - run:
          name: Deploy to Clojars
          command: clojure -X:jar:deploy
          working_directory: lib

  test-app:
    executor: clj
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Dependencies
          command: clojure -X:test:junit:deps prep
          working_directory: app
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "app/deps.edn" }}
      - run:
          name: Unit tests
          command: clojure -M:test:junit
          working_directory: app
      - store_test_results:
          path: app/junit.xml

  test-hook:
    executor: cljs
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-hook-{{ checksum "hook/shadow-cljs.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-hook-
      - run:
          name: Dependencies
          command: npm install
          working_directory: hook
      - save_cache:
          paths:
            - hook/node-modules
          key: v1-dependencies-hook-{{ checksum "hook/shadow-cljs.edn" }}
      - run:
          name: Compile
          command: npx shadow-cljs compile test
          working_directory: hook
      - run:
          name: Unit tests
          command: node out/node-tests.js
          working_directory: hook
        # TODO Output as junit or another format CircleCI can understand
          
workflows:
  version: 2
  full-build:
    jobs:
      - test-script-lib
      - deploy-script-lib:
          context: clojars-monkeyci
          requires:
            - test-script-lib
      - test-app:
          context: docker
          requires:
            - deploy-script-lib
      - test-hook:
          context: docker
