CREATE TABLE repos (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  uuid BINARY(16) NOT NULL,
  customer_id INTEGER NOT NULL,
  name VARCHAR(200),
  url VARCHAR(300),
  FOREIGN KEY (customer_id) REFERENCES customers(id)
);
