CREATE TABLE builds (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
  uuid UUID NOT NULL,
  repo_id INTEGER NOT NULL,
  jobs CLOB, -- FIXME This type does not exist in mysql
  FOREIGN KEY (repo_id) REFERENCES repos(id)
);
