#!/bin/bash -e

clj -T:uberjar

UBERJAR=target/monkeyci-cli.jar

native-image -cp $UBERJAR -jar $UBERJAR \
  -J-Dclojure.spec.skip.macros=true \
  -J-Dclojure.compiler.direct-linking=true \
  --initialize-at-build-time \
  --no-fallback \
  -march=native \
  monkeyci

