(ns monkey.ci.containers.log-ingest
  "Event handlers that tail log files generated by build commands"
  (:require [babashka.fs :as fs]
            [clojure.tools.logging :as log]
            [manifold.stream :as ms]
            [medley.core :as mc]
            [monkey.ci.events.mailman :as mm]
            [monkey.ci.logging.log-ingest :as li]
            [monkey.ci.events.mailman.interceptors :as mi]))

(def get-std-files (juxt :stdout :stderr))

(def get-stream-creator ::stream-creator)

(defn set-stream-creator [ctx sc]
  (assoc ctx ::stream-creator sc))

(def get-ingest-streams ::ingest-streams)

(defn add-ingest-streams [ctx s]
  (update ctx ::ingest-streams merge (->> (group-by :path s)
                                          (mc/map-vals first))))

(defn remove-ingest-streams [ctx s]
  (let [f (set (map :path s))]
    (update ctx ::ingest-streams (partial mc/remove-keys f))))

(defn- ingest-file
  "Starts ingesting log entries from given file into stream `s`."
  [f s]
  ;; TODO Pass additional streaming options
  (log/debug "Starting to ingest logs from:" f)
  {:path f
   :stream s
   :result (li/stream-file-when-exists f s)})

(defn- ingest-all [ctx files]
  (->> files
       ;; Only ingest files where the dir exists.  The file may not exist at this point yet.
       (filter (comp fs/exists? fs/parent))
       (map (fn [f]
              ;; TODO Pass job details to stream creator
              [f ((get-stream-creator ctx) f)]))
       (map (partial apply ingest-file))))

(defn- stop-ingest-all [ctx files]
  (let [r (get-ingest-streams ctx)]
    (letfn [(close-stream [f]
              (when-let [v (get r f)]
                (log/debug "Stopping log ingestion from:" f)
                (ms/close! (:stream v))
                v))]
      (->> files
           (filter fs/exists?)
           (map close-stream)
           (remove nil?)
           (doall)))))

;;; Interceptors

(def start-ingest
  {:name ::start-ingest
   :leave (fn [ctx]
            (if-let [r (get (mi/get-result ctx) :ingest/start)]
              (-> ctx
                  (add-ingest-streams (ingest-all ctx r))
                  (mi/set-result nil))
              ctx))})

(def stop-ingest
  {:name ::stop-ingest
   :leave (fn [ctx]
            (if-let [r (get (mi/get-result ctx) :ingest/stop)]
              (-> ctx
                  (remove-ingest-streams (stop-ingest-all ctx r))
                  (mi/set-result nil))
              ctx))})

;;; Event handlers

(defn command-start [ctx]
  {:ingest/start (get-std-files (:event ctx))})

(defn command-end [ctx]
  {:ingest/stop (get-std-files (:event ctx))})

;;; Routing

(defn make-routes
  "Creates Mailman routes to handle command events for log ingestion."
  [conf]
  [[:command/start
    [{:handler command-start
      :interceptors [start-ingest]}]]

   [:command/end
    [{:handler command-end
      :interceptors [stop-ingest]}]]])
